### ISSUE TITLE
Besta RTOS reversing

### ISSUE THREAD

**Issue by dogtopus** [0x90nz/0x90nz#1]
Please forgive me if this is not the right place to post this, but I can't find a way to contact you so there we go...

I saw your blog post about your [reverse engineering on Besta RTOS](https://blog.nop.nz/posts/win-ce/). I am actually doing the same thing recently but with another machine type (BA110L). I was able to exploit the system's MMU-less nature (probably similar to what uCLinux did but a lot jankier) to dump the whole physical SDRAM region. What I found is that it's probably not running pure Windows CE/NK, but rather probably a heavily patched NK with MMU requirements removed and a "PIE" loader that relocates the executable by patching the offsets in the binary in an unknown pattern. This is unfortunately the most significant roadblock for me too in terms of homebrew development as in I need to resort to abusing immediates to load any constants properly.

I also got MaxKellermann's [arm-mingw32ce-gcc fork](https://github.com/MaxKellermann/cegcc-build) to compile and hopefully it would be useful later. Currently I'm still trying to get arm-none-eabi-gcc to compile working shellcodes for me.

It would be nice if we can collaborate on this further.

**Comment by 0x90nz** [comment]
Nice work, you've certainly gotten further than I ever did.

I've not really had time to mess around with it since that post, so pretty much everything I know is there. Binaries having their offsets patched certainly explains the weirdness I saw.

You can find my email address on the home page of [my website](https://nop.nz/) under "Email", which is probably the best way to reach me if you want to continue the discussion.

**Comment by dogtopus** [comment]
OK sent you an email.
